-- 2026-09-28 채용공고 근무 지역을 시·도(region)·시·군·구(sub_region) enum으로 바꾼다
--
-- 기존 DB에 한 번만 실행한다. 운영은 ddl-auto=none이므로 두 API를 배포하기 전에 적용한다.
-- 이 SQL이 없으면 엔티티가 없는 sub_region 컬럼을 읽어 채용공고 조회가 500이 되고,
-- 원문 문자열이 남은 region을 enum으로 읽지 못한다.
--
-- 기존 region은 크롤러·고용24·기업회원이 보낸 원문(예: `서울 강남구`, `경기도 화성시 동탄구`)이다.
-- 원문의 앞부분을 시·도와 시·군·구 이름에 맞춰 옮기고, 맞는 값이 없으면 null로 둔다.
-- - 시·도는 짧은 이름(서울), 전체 이름(서울특별시), 통합·개편 전 이름(광주·전남, 강원도, 전라북도)을 받는다.
-- - 일반구(`경기 수원시 장안구`)는 소속 시(GYEONGGI_SUWON_SI)로 옮긴다.
-- - 인천의 개편 전 중구·동구·서구는 새 구와 일대일로 대응하지 않아 시·도(INCHEON)만 남긴다.

-- 로컬처럼 ddl-auto=update로 sub_region 컬럼과 인덱스가 이미 생긴 DB는 2단계의 alter와 4단계를 건너뛰고 나머지를 실행한다.

-- 1. 현재 상태를 확인한다. region이 이미 `SEOUL`처럼 enum 이름이면 적용된 DB이므로 실행하지 않는다.
show columns from jobs like '%region';
select region, count(*) from jobs group by region order by count(*) desc;

-- 2. 시·군·구 컬럼을 추가하고 원문에서 옮긴다. 시·도를 옮기면 원문이 사라지므로 시·군·구를 먼저 옮긴다.
alter table jobs
    add column sub_region varchar(40) null after region;

update jobs
set sub_region = case
        when region like '서울특별시 종로구%' or region like '서울 종로구%' then 'SEOUL_JONGNO_GU'
        when region like '서울특별시 중구%' or region like '서울 중구%' then 'SEOUL_JUNG_GU'
        when region like '서울특별시 용산구%' or region like '서울 용산구%' then 'SEOUL_YONGSAN_GU'
        when region like '서울특별시 성동구%' or region like '서울 성동구%' then 'SEOUL_SEONGDONG_GU'
        when region like '서울특별시 광진구%' or region like '서울 광진구%' then 'SEOUL_GWANGJIN_GU'
        when region like '서울특별시 동대문구%' or region like '서울 동대문구%' then 'SEOUL_DONGDAEMUN_GU'
        when region like '서울특별시 중랑구%' or region like '서울 중랑구%' then 'SEOUL_JUNGNANG_GU'
        when region like '서울특별시 성북구%' or region like '서울 성북구%' then 'SEOUL_SEONGBUK_GU'
        when region like '서울특별시 강북구%' or region like '서울 강북구%' then 'SEOUL_GANGBUK_GU'
        when region like '서울특별시 도봉구%' or region like '서울 도봉구%' then 'SEOUL_DOBONG_GU'
        when region like '서울특별시 노원구%' or region like '서울 노원구%' then 'SEOUL_NOWON_GU'
        when region like '서울특별시 은평구%' or region like '서울 은평구%' then 'SEOUL_EUNPYEONG_GU'
        when region like '서울특별시 서대문구%' or region like '서울 서대문구%' then 'SEOUL_SEODAEMUN_GU'
        when region like '서울특별시 마포구%' or region like '서울 마포구%' then 'SEOUL_MAPO_GU'
        when region like '서울특별시 양천구%' or region like '서울 양천구%' then 'SEOUL_YANGCHEON_GU'
        when region like '서울특별시 강서구%' or region like '서울 강서구%' then 'SEOUL_GANGSEO_GU'
        when region like '서울특별시 구로구%' or region like '서울 구로구%' then 'SEOUL_GURO_GU'
        when region like '서울특별시 금천구%' or region like '서울 금천구%' then 'SEOUL_GEUMCHEON_GU'
        when region like '서울특별시 영등포구%' or region like '서울 영등포구%' then 'SEOUL_YEONGDEUNGPO_GU'
        when region like '서울특별시 동작구%' or region like '서울 동작구%' then 'SEOUL_DONGJAK_GU'
        when region like '서울특별시 관악구%' or region like '서울 관악구%' then 'SEOUL_GWANAK_GU'
        when region like '서울특별시 서초구%' or region like '서울 서초구%' then 'SEOUL_SEOCHO_GU'
        when region like '서울특별시 강남구%' or region like '서울 강남구%' then 'SEOUL_GANGNAM_GU'
        when region like '서울특별시 송파구%' or region like '서울 송파구%' then 'SEOUL_SONGPA_GU'
        when region like '서울특별시 강동구%' or region like '서울 강동구%' then 'SEOUL_GANGDONG_GU'
        when region like '경기도 수원시%' or region like '경기 수원시%' then 'GYEONGGI_SUWON_SI'
        when region like '경기도 성남시%' or region like '경기 성남시%' then 'GYEONGGI_SEONGNAM_SI'
        when region like '경기도 의정부시%' or region like '경기 의정부시%' then 'GYEONGGI_UIJEONGBU_SI'
        when region like '경기도 안양시%' or region like '경기 안양시%' then 'GYEONGGI_ANYANG_SI'
        when region like '경기도 부천시%' or region like '경기 부천시%' then 'GYEONGGI_BUCHEON_SI'
        when region like '경기도 광명시%' or region like '경기 광명시%' then 'GYEONGGI_GWANGMYEONG_SI'
        when region like '경기도 평택시%' or region like '경기 평택시%' then 'GYEONGGI_PYEONGTAEK_SI'
        when region like '경기도 동두천시%' or region like '경기 동두천시%' then 'GYEONGGI_DONGDUCHEON_SI'
        when region like '경기도 안산시%' or region like '경기 안산시%' then 'GYEONGGI_ANSAN_SI'
        when region like '경기도 고양시%' or region like '경기 고양시%' then 'GYEONGGI_GOYANG_SI'
        when region like '경기도 과천시%' or region like '경기 과천시%' then 'GYEONGGI_GWACHEON_SI'
        when region like '경기도 구리시%' or region like '경기 구리시%' then 'GYEONGGI_GURI_SI'
        when region like '경기도 남양주시%' or region like '경기 남양주시%' then 'GYEONGGI_NAMYANGJU_SI'
        when region like '경기도 오산시%' or region like '경기 오산시%' then 'GYEONGGI_OSAN_SI'
        when region like '경기도 시흥시%' or region like '경기 시흥시%' then 'GYEONGGI_SIHEUNG_SI'
        when region like '경기도 군포시%' or region like '경기 군포시%' then 'GYEONGGI_GUNPO_SI'
        when region like '경기도 의왕시%' or region like '경기 의왕시%' then 'GYEONGGI_UIWANG_SI'
        when region like '경기도 하남시%' or region like '경기 하남시%' then 'GYEONGGI_HANAM_SI'
        when region like '경기도 용인시%' or region like '경기 용인시%' then 'GYEONGGI_YONGIN_SI'
        when region like '경기도 파주시%' or region like '경기 파주시%' then 'GYEONGGI_PAJU_SI'
        when region like '경기도 이천시%' or region like '경기 이천시%' then 'GYEONGGI_ICHEON_SI'
        when region like '경기도 안성시%' or region like '경기 안성시%' then 'GYEONGGI_ANSEONG_SI'
        when region like '경기도 김포시%' or region like '경기 김포시%' then 'GYEONGGI_GIMPO_SI'
        when region like '경기도 화성시%' or region like '경기 화성시%' then 'GYEONGGI_HWASEONG_SI'
        when region like '경기도 광주시%' or region like '경기 광주시%' then 'GYEONGGI_GWANGJU_SI'
        when region like '경기도 양주시%' or region like '경기 양주시%' then 'GYEONGGI_YANGJU_SI'
        when region like '경기도 포천시%' or region like '경기 포천시%' then 'GYEONGGI_POCHEON_SI'
        when region like '경기도 여주시%' or region like '경기 여주시%' then 'GYEONGGI_YEOJU_SI'
        when region like '경기도 연천군%' or region like '경기 연천군%' then 'GYEONGGI_YEONCHEON_GUN'
        when region like '경기도 가평군%' or region like '경기 가평군%' then 'GYEONGGI_GAPYEONG_GUN'
        when region like '경기도 양평군%' or region like '경기 양평군%' then 'GYEONGGI_YANGPYEONG_GUN'
        when region like '인천광역시 제물포구%' or region like '인천 제물포구%' then 'INCHEON_JEMULPO_GU'
        when region like '인천광역시 영종구%' or region like '인천 영종구%' then 'INCHEON_YEONGJONG_GU'
        when region like '인천광역시 미추홀구%' or region like '인천 미추홀구%' then 'INCHEON_MICHUHOL_GU'
        when region like '인천광역시 연수구%' or region like '인천 연수구%' then 'INCHEON_YEONSU_GU'
        when region like '인천광역시 남동구%' or region like '인천 남동구%' then 'INCHEON_NAMDONG_GU'
        when region like '인천광역시 부평구%' or region like '인천 부평구%' then 'INCHEON_BUPYEONG_GU'
        when region like '인천광역시 계양구%' or region like '인천 계양구%' then 'INCHEON_GYEYANG_GU'
        when region like '인천광역시 서해구%' or region like '인천 서해구%' then 'INCHEON_SEOHAE_GU'
        when region like '인천광역시 검단구%' or region like '인천 검단구%' then 'INCHEON_GEOMDAN_GU'
        when region like '인천광역시 강화군%' or region like '인천 강화군%' then 'INCHEON_GANGHWA_GUN'
        when region like '인천광역시 옹진군%' or region like '인천 옹진군%' then 'INCHEON_ONGJIN_GUN'
        when region like '부산광역시 중구%' or region like '부산 중구%' then 'BUSAN_JUNG_GU'
        when region like '부산광역시 서구%' or region like '부산 서구%' then 'BUSAN_SEO_GU'
        when region like '부산광역시 동구%' or region like '부산 동구%' then 'BUSAN_DONG_GU'
        when region like '부산광역시 영도구%' or region like '부산 영도구%' then 'BUSAN_YEONGDO_GU'
        when region like '부산광역시 부산진구%' or region like '부산 부산진구%' then 'BUSAN_BUSANJIN_GU'
        when region like '부산광역시 동래구%' or region like '부산 동래구%' then 'BUSAN_DONGNAE_GU'
        when region like '부산광역시 남구%' or region like '부산 남구%' then 'BUSAN_NAM_GU'
        when region like '부산광역시 북구%' or region like '부산 북구%' then 'BUSAN_BUK_GU'
        when region like '부산광역시 해운대구%' or region like '부산 해운대구%' then 'BUSAN_HAEUNDAE_GU'
        when region like '부산광역시 사하구%' or region like '부산 사하구%' then 'BUSAN_SAHA_GU'
        when region like '부산광역시 금정구%' or region like '부산 금정구%' then 'BUSAN_GEUMJEONG_GU'
        when region like '부산광역시 강서구%' or region like '부산 강서구%' then 'BUSAN_GANGSEO_GU'
        when region like '부산광역시 연제구%' or region like '부산 연제구%' then 'BUSAN_YEONJE_GU'
        when region like '부산광역시 수영구%' or region like '부산 수영구%' then 'BUSAN_SUYEONG_GU'
        when region like '부산광역시 사상구%' or region like '부산 사상구%' then 'BUSAN_SASANG_GU'
        when region like '부산광역시 기장군%' or region like '부산 기장군%' then 'BUSAN_GIJANG_GUN'
        when region like '대구광역시 중구%' or region like '대구 중구%' then 'DAEGU_JUNG_GU'
        when region like '대구광역시 동구%' or region like '대구 동구%' then 'DAEGU_DONG_GU'
        when region like '대구광역시 서구%' or region like '대구 서구%' then 'DAEGU_SEO_GU'
        when region like '대구광역시 남구%' or region like '대구 남구%' then 'DAEGU_NAM_GU'
        when region like '대구광역시 북구%' or region like '대구 북구%' then 'DAEGU_BUK_GU'
        when region like '대구광역시 수성구%' or region like '대구 수성구%' then 'DAEGU_SUSEONG_GU'
        when region like '대구광역시 달서구%' or region like '대구 달서구%' then 'DAEGU_DALSEO_GU'
        when region like '대구광역시 달성군%' or region like '대구 달성군%' then 'DAEGU_DALSEONG_GUN'
        when region like '대구광역시 군위군%' or region like '대구 군위군%' then 'DAEGU_GUNWI_GUN'
        when region like '전남광주통합특별시 목포시%' or region like '전남광주 목포시%' or region like '광주광역시 목포시%' or region like '광주 목포시%' or region like '전라남도 목포시%' or region like '전남 목포시%' then 'JEONNAM_GWANGJU_MOKPO_SI'
        when region like '전남광주통합특별시 여수시%' or region like '전남광주 여수시%' or region like '광주광역시 여수시%' or region like '광주 여수시%' or region like '전라남도 여수시%' or region like '전남 여수시%' then 'JEONNAM_GWANGJU_YEOSU_SI'
        when region like '전남광주통합특별시 순천시%' or region like '전남광주 순천시%' or region like '광주광역시 순천시%' or region like '광주 순천시%' or region like '전라남도 순천시%' or region like '전남 순천시%' then 'JEONNAM_GWANGJU_SUNCHEON_SI'
        when region like '전남광주통합특별시 나주시%' or region like '전남광주 나주시%' or region like '광주광역시 나주시%' or region like '광주 나주시%' or region like '전라남도 나주시%' or region like '전남 나주시%' then 'JEONNAM_GWANGJU_NAJU_SI'
        when region like '전남광주통합특별시 광양시%' or region like '전남광주 광양시%' or region like '광주광역시 광양시%' or region like '광주 광양시%' or region like '전라남도 광양시%' or region like '전남 광양시%' then 'JEONNAM_GWANGJU_GWANGYANG_SI'
        when region like '전남광주통합특별시 동구%' or region like '전남광주 동구%' or region like '광주광역시 동구%' or region like '광주 동구%' or region like '전라남도 동구%' or region like '전남 동구%' then 'JEONNAM_GWANGJU_DONG_GU'
        when region like '전남광주통합특별시 서구%' or region like '전남광주 서구%' or region like '광주광역시 서구%' or region like '광주 서구%' or region like '전라남도 서구%' or region like '전남 서구%' then 'JEONNAM_GWANGJU_SEO_GU'
        when region like '전남광주통합특별시 남구%' or region like '전남광주 남구%' or region like '광주광역시 남구%' or region like '광주 남구%' or region like '전라남도 남구%' or region like '전남 남구%' then 'JEONNAM_GWANGJU_NAM_GU'
        when region like '전남광주통합특별시 북구%' or region like '전남광주 북구%' or region like '광주광역시 북구%' or region like '광주 북구%' or region like '전라남도 북구%' or region like '전남 북구%' then 'JEONNAM_GWANGJU_BUK_GU'
        when region like '전남광주통합특별시 광산구%' or region like '전남광주 광산구%' or region like '광주광역시 광산구%' or region like '광주 광산구%' or region like '전라남도 광산구%' or region like '전남 광산구%' then 'JEONNAM_GWANGJU_GWANGSAN_GU'
        when region like '전남광주통합특별시 담양군%' or region like '전남광주 담양군%' or region like '광주광역시 담양군%' or region like '광주 담양군%' or region like '전라남도 담양군%' or region like '전남 담양군%' then 'JEONNAM_GWANGJU_DAMYANG_GUN'
        when region like '전남광주통합특별시 곡성군%' or region like '전남광주 곡성군%' or region like '광주광역시 곡성군%' or region like '광주 곡성군%' or region like '전라남도 곡성군%' or region like '전남 곡성군%' then 'JEONNAM_GWANGJU_GOKSEONG_GUN'
        when region like '전남광주통합특별시 구례군%' or region like '전남광주 구례군%' or region like '광주광역시 구례군%' or region like '광주 구례군%' or region like '전라남도 구례군%' or region like '전남 구례군%' then 'JEONNAM_GWANGJU_GURYE_GUN'
        when region like '전남광주통합특별시 고흥군%' or region like '전남광주 고흥군%' or region like '광주광역시 고흥군%' or region like '광주 고흥군%' or region like '전라남도 고흥군%' or region like '전남 고흥군%' then 'JEONNAM_GWANGJU_GOHEUNG_GUN'
        when region like '전남광주통합특별시 보성군%' or region like '전남광주 보성군%' or region like '광주광역시 보성군%' or region like '광주 보성군%' or region like '전라남도 보성군%' or region like '전남 보성군%' then 'JEONNAM_GWANGJU_BOSEONG_GUN'
        when region like '전남광주통합특별시 화순군%' or region like '전남광주 화순군%' or region like '광주광역시 화순군%' or region like '광주 화순군%' or region like '전라남도 화순군%' or region like '전남 화순군%' then 'JEONNAM_GWANGJU_HWASUN_GUN'
        when region like '전남광주통합특별시 장흥군%' or region like '전남광주 장흥군%' or region like '광주광역시 장흥군%' or region like '광주 장흥군%' or region like '전라남도 장흥군%' or region like '전남 장흥군%' then 'JEONNAM_GWANGJU_JANGHEUNG_GUN'
        when region like '전남광주통합특별시 강진군%' or region like '전남광주 강진군%' or region like '광주광역시 강진군%' or region like '광주 강진군%' or region like '전라남도 강진군%' or region like '전남 강진군%' then 'JEONNAM_GWANGJU_GANGJIN_GUN'
        when region like '전남광주통합특별시 해남군%' or region like '전남광주 해남군%' or region like '광주광역시 해남군%' or region like '광주 해남군%' or region like '전라남도 해남군%' or region like '전남 해남군%' then 'JEONNAM_GWANGJU_HAENAM_GUN'
        when region like '전남광주통합특별시 영암군%' or region like '전남광주 영암군%' or region like '광주광역시 영암군%' or region like '광주 영암군%' or region like '전라남도 영암군%' or region like '전남 영암군%' then 'JEONNAM_GWANGJU_YEONGAM_GUN'
        when region like '전남광주통합특별시 무안군%' or region like '전남광주 무안군%' or region like '광주광역시 무안군%' or region like '광주 무안군%' or region like '전라남도 무안군%' or region like '전남 무안군%' then 'JEONNAM_GWANGJU_MUAN_GUN'
        when region like '전남광주통합특별시 함평군%' or region like '전남광주 함평군%' or region like '광주광역시 함평군%' or region like '광주 함평군%' or region like '전라남도 함평군%' or region like '전남 함평군%' then 'JEONNAM_GWANGJU_HAMPYEONG_GUN'
        when region like '전남광주통합특별시 영광군%' or region like '전남광주 영광군%' or region like '광주광역시 영광군%' or region like '광주 영광군%' or region like '전라남도 영광군%' or region like '전남 영광군%' then 'JEONNAM_GWANGJU_YEONGGWANG_GUN'
        when region like '전남광주통합특별시 장성군%' or region like '전남광주 장성군%' or region like '광주광역시 장성군%' or region like '광주 장성군%' or region like '전라남도 장성군%' or region like '전남 장성군%' then 'JEONNAM_GWANGJU_JANGSEONG_GUN'
        when region like '전남광주통합특별시 완도군%' or region like '전남광주 완도군%' or region like '광주광역시 완도군%' or region like '광주 완도군%' or region like '전라남도 완도군%' or region like '전남 완도군%' then 'JEONNAM_GWANGJU_WANDO_GUN'
        when region like '전남광주통합특별시 진도군%' or region like '전남광주 진도군%' or region like '광주광역시 진도군%' or region like '광주 진도군%' or region like '전라남도 진도군%' or region like '전남 진도군%' then 'JEONNAM_GWANGJU_JINDO_GUN'
        when region like '전남광주통합특별시 신안군%' or region like '전남광주 신안군%' or region like '광주광역시 신안군%' or region like '광주 신안군%' or region like '전라남도 신안군%' or region like '전남 신안군%' then 'JEONNAM_GWANGJU_SINAN_GUN'
        when region like '대전광역시 동구%' or region like '대전 동구%' then 'DAEJEON_DONG_GU'
        when region like '대전광역시 중구%' or region like '대전 중구%' then 'DAEJEON_JUNG_GU'
        when region like '대전광역시 서구%' or region like '대전 서구%' then 'DAEJEON_SEO_GU'
        when region like '대전광역시 유성구%' or region like '대전 유성구%' then 'DAEJEON_YUSEONG_GU'
        when region like '대전광역시 대덕구%' or region like '대전 대덕구%' then 'DAEJEON_DAEDEOK_GU'
        when region like '울산광역시 중구%' or region like '울산 중구%' then 'ULSAN_JUNG_GU'
        when region like '울산광역시 남구%' or region like '울산 남구%' then 'ULSAN_NAM_GU'
        when region like '울산광역시 동구%' or region like '울산 동구%' then 'ULSAN_DONG_GU'
        when region like '울산광역시 북구%' or region like '울산 북구%' then 'ULSAN_BUK_GU'
        when region like '울산광역시 울주군%' or region like '울산 울주군%' then 'ULSAN_ULJU_GUN'
        when region like '강원특별자치도 춘천시%' or region like '강원도 춘천시%' or region like '강원 춘천시%' then 'GANGWON_CHUNCHEON_SI'
        when region like '강원특별자치도 원주시%' or region like '강원도 원주시%' or region like '강원 원주시%' then 'GANGWON_WONJU_SI'
        when region like '강원특별자치도 강릉시%' or region like '강원도 강릉시%' or region like '강원 강릉시%' then 'GANGWON_GANGNEUNG_SI'
        when region like '강원특별자치도 동해시%' or region like '강원도 동해시%' or region like '강원 동해시%' then 'GANGWON_DONGHAE_SI'
        when region like '강원특별자치도 태백시%' or region like '강원도 태백시%' or region like '강원 태백시%' then 'GANGWON_TAEBAEK_SI'
        when region like '강원특별자치도 속초시%' or region like '강원도 속초시%' or region like '강원 속초시%' then 'GANGWON_SOKCHO_SI'
        when region like '강원특별자치도 삼척시%' or region like '강원도 삼척시%' or region like '강원 삼척시%' then 'GANGWON_SAMCHEOK_SI'
        when region like '강원특별자치도 홍천군%' or region like '강원도 홍천군%' or region like '강원 홍천군%' then 'GANGWON_HONGCHEON_GUN'
        when region like '강원특별자치도 횡성군%' or region like '강원도 횡성군%' or region like '강원 횡성군%' then 'GANGWON_HOENGSEONG_GUN'
        when region like '강원특별자치도 영월군%' or region like '강원도 영월군%' or region like '강원 영월군%' then 'GANGWON_YEONGWOL_GUN'
        when region like '강원특별자치도 평창군%' or region like '강원도 평창군%' or region like '강원 평창군%' then 'GANGWON_PYEONGCHANG_GUN'
        when region like '강원특별자치도 정선군%' or region like '강원도 정선군%' or region like '강원 정선군%' then 'GANGWON_JEONGSEON_GUN'
        when region like '강원특별자치도 철원군%' or region like '강원도 철원군%' or region like '강원 철원군%' then 'GANGWON_CHEORWON_GUN'
        when region like '강원특별자치도 화천군%' or region like '강원도 화천군%' or region like '강원 화천군%' then 'GANGWON_HWACHEON_GUN'
        when region like '강원특별자치도 양구군%' or region like '강원도 양구군%' or region like '강원 양구군%' then 'GANGWON_YANGGU_GUN'
        when region like '강원특별자치도 인제군%' or region like '강원도 인제군%' or region like '강원 인제군%' then 'GANGWON_INJE_GUN'
        when region like '강원특별자치도 고성군%' or region like '강원도 고성군%' or region like '강원 고성군%' then 'GANGWON_GOSEONG_GUN'
        when region like '강원특별자치도 양양군%' or region like '강원도 양양군%' or region like '강원 양양군%' then 'GANGWON_YANGYANG_GUN'
        when region like '경상남도 창원시%' or region like '경남 창원시%' then 'GYEONGNAM_CHANGWON_SI'
        when region like '경상남도 진주시%' or region like '경남 진주시%' then 'GYEONGNAM_JINJU_SI'
        when region like '경상남도 통영시%' or region like '경남 통영시%' then 'GYEONGNAM_TONGYEONG_SI'
        when region like '경상남도 사천시%' or region like '경남 사천시%' then 'GYEONGNAM_SACHEON_SI'
        when region like '경상남도 김해시%' or region like '경남 김해시%' then 'GYEONGNAM_GIMHAE_SI'
        when region like '경상남도 밀양시%' or region like '경남 밀양시%' then 'GYEONGNAM_MIRYANG_SI'
        when region like '경상남도 거제시%' or region like '경남 거제시%' then 'GYEONGNAM_GEOJE_SI'
        when region like '경상남도 양산시%' or region like '경남 양산시%' then 'GYEONGNAM_YANGSAN_SI'
        when region like '경상남도 의령군%' or region like '경남 의령군%' then 'GYEONGNAM_UIRYEONG_GUN'
        when region like '경상남도 함안군%' or region like '경남 함안군%' then 'GYEONGNAM_HAMAN_GUN'
        when region like '경상남도 창녕군%' or region like '경남 창녕군%' then 'GYEONGNAM_CHANGNYEONG_GUN'
        when region like '경상남도 고성군%' or region like '경남 고성군%' then 'GYEONGNAM_GOSEONG_GUN'
        when region like '경상남도 남해군%' or region like '경남 남해군%' then 'GYEONGNAM_NAMHAE_GUN'
        when region like '경상남도 하동군%' or region like '경남 하동군%' then 'GYEONGNAM_HADONG_GUN'
        when region like '경상남도 산청군%' or region like '경남 산청군%' then 'GYEONGNAM_SANCHEONG_GUN'
        when region like '경상남도 함양군%' or region like '경남 함양군%' then 'GYEONGNAM_HAMYANG_GUN'
        when region like '경상남도 거창군%' or region like '경남 거창군%' then 'GYEONGNAM_GEOCHANG_GUN'
        when region like '경상남도 합천군%' or region like '경남 합천군%' then 'GYEONGNAM_HAPCHEON_GUN'
        when region like '경상북도 포항시%' or region like '경북 포항시%' then 'GYEONGBUK_POHANG_SI'
        when region like '경상북도 경주시%' or region like '경북 경주시%' then 'GYEONGBUK_GYEONGJU_SI'
        when region like '경상북도 김천시%' or region like '경북 김천시%' then 'GYEONGBUK_GIMCHEON_SI'
        when region like '경상북도 안동시%' or region like '경북 안동시%' then 'GYEONGBUK_ANDONG_SI'
        when region like '경상북도 구미시%' or region like '경북 구미시%' then 'GYEONGBUK_GUMI_SI'
        when region like '경상북도 영주시%' or region like '경북 영주시%' then 'GYEONGBUK_YEONGJU_SI'
        when region like '경상북도 영천시%' or region like '경북 영천시%' then 'GYEONGBUK_YEONGCHEON_SI'
        when region like '경상북도 상주시%' or region like '경북 상주시%' then 'GYEONGBUK_SANGJU_SI'
        when region like '경상북도 문경시%' or region like '경북 문경시%' then 'GYEONGBUK_MUNGYEONG_SI'
        when region like '경상북도 경산시%' or region like '경북 경산시%' then 'GYEONGBUK_GYEONGSAN_SI'
        when region like '경상북도 의성군%' or region like '경북 의성군%' then 'GYEONGBUK_UISEONG_GUN'
        when region like '경상북도 청송군%' or region like '경북 청송군%' then 'GYEONGBUK_CHEONGSONG_GUN'
        when region like '경상북도 영양군%' or region like '경북 영양군%' then 'GYEONGBUK_YEONGYANG_GUN'
        when region like '경상북도 영덕군%' or region like '경북 영덕군%' then 'GYEONGBUK_YEONGDEOK_GUN'
        when region like '경상북도 청도군%' or region like '경북 청도군%' then 'GYEONGBUK_CHEONGDO_GUN'
        when region like '경상북도 고령군%' or region like '경북 고령군%' then 'GYEONGBUK_GORYEONG_GUN'
        when region like '경상북도 성주군%' or region like '경북 성주군%' then 'GYEONGBUK_SEONGJU_GUN'
        when region like '경상북도 칠곡군%' or region like '경북 칠곡군%' then 'GYEONGBUK_CHILGOK_GUN'
        when region like '경상북도 예천군%' or region like '경북 예천군%' then 'GYEONGBUK_YECHEON_GUN'
        when region like '경상북도 봉화군%' or region like '경북 봉화군%' then 'GYEONGBUK_BONGHWA_GUN'
        when region like '경상북도 울진군%' or region like '경북 울진군%' then 'GYEONGBUK_ULJIN_GUN'
        when region like '경상북도 울릉군%' or region like '경북 울릉군%' then 'GYEONGBUK_ULLEUNG_GUN'
        when region like '충청남도 천안시%' or region like '충남 천안시%' then 'CHUNGNAM_CHEONAN_SI'
        when region like '충청남도 공주시%' or region like '충남 공주시%' then 'CHUNGNAM_GONGJU_SI'
        when region like '충청남도 보령시%' or region like '충남 보령시%' then 'CHUNGNAM_BORYEONG_SI'
        when region like '충청남도 아산시%' or region like '충남 아산시%' then 'CHUNGNAM_ASAN_SI'
        when region like '충청남도 서산시%' or region like '충남 서산시%' then 'CHUNGNAM_SEOSAN_SI'
        when region like '충청남도 논산시%' or region like '충남 논산시%' then 'CHUNGNAM_NONSAN_SI'
        when region like '충청남도 계룡시%' or region like '충남 계룡시%' then 'CHUNGNAM_GYERYONG_SI'
        when region like '충청남도 당진시%' or region like '충남 당진시%' then 'CHUNGNAM_DANGJIN_SI'
        when region like '충청남도 금산군%' or region like '충남 금산군%' then 'CHUNGNAM_GEUMSAN_GUN'
        when region like '충청남도 부여군%' or region like '충남 부여군%' then 'CHUNGNAM_BUYEO_GUN'
        when region like '충청남도 서천군%' or region like '충남 서천군%' then 'CHUNGNAM_SEOCHEON_GUN'
        when region like '충청남도 청양군%' or region like '충남 청양군%' then 'CHUNGNAM_CHEONGYANG_GUN'
        when region like '충청남도 홍성군%' or region like '충남 홍성군%' then 'CHUNGNAM_HONGSEONG_GUN'
        when region like '충청남도 예산군%' or region like '충남 예산군%' then 'CHUNGNAM_YESAN_GUN'
        when region like '충청남도 태안군%' or region like '충남 태안군%' then 'CHUNGNAM_TAEAN_GUN'
        when region like '충청북도 청주시%' or region like '충북 청주시%' then 'CHUNGBUK_CHEONGJU_SI'
        when region like '충청북도 충주시%' or region like '충북 충주시%' then 'CHUNGBUK_CHUNGJU_SI'
        when region like '충청북도 제천시%' or region like '충북 제천시%' then 'CHUNGBUK_JECHEON_SI'
        when region like '충청북도 보은군%' or region like '충북 보은군%' then 'CHUNGBUK_BOEUN_GUN'
        when region like '충청북도 옥천군%' or region like '충북 옥천군%' then 'CHUNGBUK_OKCHEON_GUN'
        when region like '충청북도 영동군%' or region like '충북 영동군%' then 'CHUNGBUK_YEONGDONG_GUN'
        when region like '충청북도 증평군%' or region like '충북 증평군%' then 'CHUNGBUK_JEUNGPYEONG_GUN'
        when region like '충청북도 진천군%' or region like '충북 진천군%' then 'CHUNGBUK_JINCHEON_GUN'
        when region like '충청북도 괴산군%' or region like '충북 괴산군%' then 'CHUNGBUK_GOESAN_GUN'
        when region like '충청북도 음성군%' or region like '충북 음성군%' then 'CHUNGBUK_EUMSEONG_GUN'
        when region like '충청북도 단양군%' or region like '충북 단양군%' then 'CHUNGBUK_DANYANG_GUN'
        when region like '전북특별자치도 전주시%' or region like '전라북도 전주시%' or region like '전북 전주시%' then 'JEONBUK_JEONJU_SI'
        when region like '전북특별자치도 군산시%' or region like '전라북도 군산시%' or region like '전북 군산시%' then 'JEONBUK_GUNSAN_SI'
        when region like '전북특별자치도 익산시%' or region like '전라북도 익산시%' or region like '전북 익산시%' then 'JEONBUK_IKSAN_SI'
        when region like '전북특별자치도 정읍시%' or region like '전라북도 정읍시%' or region like '전북 정읍시%' then 'JEONBUK_JEONGEUP_SI'
        when region like '전북특별자치도 남원시%' or region like '전라북도 남원시%' or region like '전북 남원시%' then 'JEONBUK_NAMWON_SI'
        when region like '전북특별자치도 김제시%' or region like '전라북도 김제시%' or region like '전북 김제시%' then 'JEONBUK_GIMJE_SI'
        when region like '전북특별자치도 완주군%' or region like '전라북도 완주군%' or region like '전북 완주군%' then 'JEONBUK_WANJU_GUN'
        when region like '전북특별자치도 진안군%' or region like '전라북도 진안군%' or region like '전북 진안군%' then 'JEONBUK_JINAN_GUN'
        when region like '전북특별자치도 무주군%' or region like '전라북도 무주군%' or region like '전북 무주군%' then 'JEONBUK_MUJU_GUN'
        when region like '전북특별자치도 장수군%' or region like '전라북도 장수군%' or region like '전북 장수군%' then 'JEONBUK_JANGSU_GUN'
        when region like '전북특별자치도 임실군%' or region like '전라북도 임실군%' or region like '전북 임실군%' then 'JEONBUK_IMSIL_GUN'
        when region like '전북특별자치도 순창군%' or region like '전라북도 순창군%' or region like '전북 순창군%' then 'JEONBUK_SUNCHANG_GUN'
        when region like '전북특별자치도 고창군%' or region like '전라북도 고창군%' or region like '전북 고창군%' then 'JEONBUK_GOCHANG_GUN'
        when region like '전북특별자치도 부안군%' or region like '전라북도 부안군%' or region like '전북 부안군%' then 'JEONBUK_BUAN_GUN'
        when region like '제주특별자치도 제주시%' or region like '제주 제주시%' then 'JEJU_JEJU_SI'
        when region like '제주특별자치도 서귀포시%' or region like '제주 서귀포시%' then 'JEJU_SEOGWIPO_SI'
    end
where region is not null;

-- 3. 원문을 시·도 enum 이름으로 바꾸고 길이를 엔티티에 맞춘다.
update jobs
set region = case
        when region like '전국%' then 'NATIONWIDE'
        when region like '서울특별시%' or region like '서울%' then 'SEOUL'
        when region like '경기도%' or region like '경기%' then 'GYEONGGI'
        when region like '인천광역시%' or region like '인천%' then 'INCHEON'
        when region like '부산광역시%' or region like '부산%' then 'BUSAN'
        when region like '대구광역시%' or region like '대구%' then 'DAEGU'
        when region like '전남광주통합특별시%' or region like '전남광주%' or region like '광주광역시%' or region like '광주%' or region like '전라남도%' or region like '전남%' then 'JEONNAM_GWANGJU'
        when region like '대전광역시%' or region like '대전%' then 'DAEJEON'
        when region like '울산광역시%' or region like '울산%' then 'ULSAN'
        when region like '세종특별자치시%' or region like '세종%' then 'SEJONG'
        when region like '강원특별자치도%' or region like '강원도%' or region like '강원%' then 'GANGWON'
        when region like '경상남도%' or region like '경남%' then 'GYEONGNAM'
        when region like '경상북도%' or region like '경북%' then 'GYEONGBUK'
        when region like '충청남도%' or region like '충남%' then 'CHUNGNAM'
        when region like '충청북도%' or region like '충북%' then 'CHUNGBUK'
        when region like '전북특별자치도%' or region like '전라북도%' or region like '전북%' then 'JEONBUK'
        when region like '제주특별자치도%' or region like '제주%' then 'JEJU'
        when region like '해외%' then 'OVERSEAS'
    end
where region is not null;

alter table jobs
    modify column region varchar(30) null;

-- 4. 목록 필터용 인덱스. 다른 필터처럼 게시 상태와 삭제 여부를 앞에 둔다.
create index idx_jobs_published_region on jobs (publication_status, deleted_at, region);
create index idx_jobs_published_sub_region on jobs (publication_status, deleted_at, sub_region);

-- 5. 결과를 확인한다. region이 null로 바뀐 행은 원문을 알 수 없던 공고다.
select region, sub_region, count(*) from jobs group by region, sub_region order by count(*) desc;
